version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
volumes:
  progresDB:
